name: Frends.FixedWidthFlatFile.ConvertToXML Main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.FixedWidthFlatFile.ConvertToXML/**'
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.FixedWidthFlatFile.ConvertToXML
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      